FROM jupyter/pyspark-notebook

ENV PYSPARK_MAJOR_PYTHON_VERSION=3

WORKDIR /opt/spark/

USER root
RUN apt-get update -yqq && \
    apt-get upgrade -yqq && \
    apt-get install -y --no-install-recommends libreoffice && \
    apt-get install -yqq --no-install-recommends 

COPY requirements.txt .
RUN pip3 install -r requirements.txt
RUN python -m pip install aspose-cells pika --upgrade

COPY . .

CMD ["python","main.py"]